version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TELEGRAM_API_ID="${API_ID}"
      - TELEGRAM_API_HASH="${b91505f49d60914689fabde26aad9f69}"
    restart: always
