version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - TELEGRAM_API_ID="${API_ID}"
      - TELEGRAM_API_HASH="${API_HASH}"
    restart: always
